# This will assign a read-only permission to an AD user to the dev1 namespace
# this role is namespace scoped
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev1
  name: dev1-full-access-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-access-rolebinding
  namespace: dev1
subjects:
  - kind: User
    name: "<AD-user-name>"
    namespace: dev1
roleRef:
  kind: Role
  name: dev1-full-access-role
  apiGroup: rbac.authorization.k8s.io
