apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-rest
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-rest
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: python-rest
    spec:
      containers:
        - name: python-rest
          image: launchbuildagent.azurecr.io/python-rest:v2
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: python-rest-secrets-store # Must match the name of the volume in the volumes section
              mountPath: "/mnt/secrets-store" # The path in the container to mount the volume
              readOnly: true
          env:
            - name: FLASK_PORT
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "otel-collector-opentelemetry-collector.default.svc.cluster.local:4317"
      volumes:
        - name: python-rest-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: python-rest-secret-provider # pragma: allowlist secret

---

apiVersion: v1
kind: Service
metadata:
  name: python-rest
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: python-rest
