apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: python-rest-secret-provider
spec:
  provider: azure # Provider of CSI driver - Azure in our case
  # the secret will be auto-created when there is any pod mounted that would need this secret and auto deleted when there are no pods referring to it
  secretObjects:
    - secretName: python-rest-secret # name of the k8s secret to be created by CSI driver # pragma: allowlist secret
      annotations:
        reloader.stakater.com/match: "true" # if reloader is configured for auto-reload of the pod, this annotation is required
      type: Opaque  # type of the k8s secret
      data:
        - objectName: applicationinsights-connection-string  # secretName in the Key-vault (can be a certificate, secret or key). Must match the objectName in the parameters - objects
          key: APPLICATIONINSIGHTS_CONNECTION_STRING  # key in the secret object in the k8s secret
        - objectName: test2
          key: test2
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "451d97c8-5b6b-41ef-925e-eed4eed28072"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "fdoc-k8s-7215383580"        # Name of the Azure KeyVault where secrets are stored
    cloudName: ""                         # if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: applicationinsights-connection-string               # The actual name of the object (secret, key or cert) in the key vault
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: test2
          objectType: secret
          objectVersion: ""
    tenantId: "c5836784-c046-4f73-9e7e-9c370262e295"
