apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-private
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-private
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer-private
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-private
subjects:
- kind: ServiceAccount
  name: external-dns-private
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-private
spec:
  selector:
    matchLabels:
      app: external-dns-private
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns-private
    spec:
      serviceAccountName: external-dns-private
      containers:
      - name: external-dns-private
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
        - --ingress-class=private-ingress
        - --source=service
        - --source=ingress
        #- --domain-filter=k8s.com
        - --provider=azure-private-dns
        - --azure-resource-group=ext-dns-rg
        - --azure-subscription-id=e71eb3cd-83f2-46eb-8f47-3b779e27672f
        volumeMounts:
        - name: azure-config-file-private
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-config-file-private
        secret:
          secretName: azure-config-file-private
